#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_QUAKEWORLD_RECORDS_USER;
	 ALTER USER $POSTGRES_QUAKEWORLD_RECORDS_USER WITH PASSWORD '$POSTGRES_QUAKEWORLD_RECORDS_USER_PASSWORD';
    CREATE DATABASE $POSTGRES_QUAKEWORLD_RECORDS_DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_QUAKEWORLD_RECORDS_DATABASE_NAME TO $POSTGRES_QUAKEWORLD_RECORDS_USER;
EOSQL