#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_QUAKEWORLD_RECORDS_USER;
	 ALTER USER $POSTGRES_QUAKEWORLD_RECORDS_USER WITH PASSWORD '$POSTGRES_QUAKEWORLD_RECORDS_USER_PASSWORD';
    CREATE DATABASE quakeworld_records;
    GRANT ALL PRIVILEGES ON DATABASE quakeworld_records TO $POSTGRES_QUAKEWORLD_RECORDS_USER;
	 CREATE DATABASE quakeworld_records_test;
    GRANT ALL PRIVILEGES ON DATABASE quakeworld_records_test TO $POSTGRES_QUAKEWORLD_RECORDS_USER;
EOSQL