#!/bin/bash
export QUAKEWORLD_RECORDS_POSTGRES_USER=postgres
export QUAKEWORLD_RECORDS_POSTGRES_PASSWORD=postgres
export POSTGRES_QUAKEWORLD_RECORDS_USER=quakeworld_records_user
export POSTGRES_QUAKEWORLD_RECORDS_USER_PASSWORD=password
export quakeworld_records_backend_jwtPrivateKey=12345678
export NODE_ENV=development